services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: devcontainer-container-name
    working_dir: /workspaces

    # ports:

    volumes:
      # We should change the path and volume name according to your project
      # when we use this template.
      - ~/devcontainer-template:/workspaces:cached
      # - ${SSH_AUTH_SOCK}:/ssh-agent

    # environment:
      # SSH_AUTH_SOCK: /ssh-agent

    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #  - seccomp:unconfined

    command: sleep infinity
